name: M3U8 Monitor

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  check_m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium

    - name: Run m3u8 monitor
      run: python monitor.py

    - name: Upload log as artifact
      uses: actions/upload-artifact@v4
      with:
        name: m3u8-log
        path: m3u8_changes.log
